-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 7.5
-- Thu Jun 22 14:33:45 2023

-- parameterized module component declaration
component ram_dp
    port (DataInA: in  std_logic_vector(15 downto 0); 
        DataInB: in  std_logic_vector(15 downto 0); 
        AddressA: in  std_logic_vector(3 downto 0); 
        AddressB: in  std_logic_vector(3 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(15 downto 0); 
        QB: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : ram_dp
    port map (DataInA(15 downto 0)=>__, DataInB(15 downto 0)=>__, 
        AddressA(3 downto 0)=>__, AddressB(3 downto 0)=>__, ClockA=>__, 
        ClockB=>__, ClockEnA=>__, ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, 
        ResetB=>__, QA(15 downto 0)=>__, QB(15 downto 0)=>__);
